# Simple container for local development

FROM node:20-alpine

# Set working directory. 
WORKDIR /app

# Install dependancies
COPY package.json package-lock.json ./
# RUN npm install
RUN npm ci

# Copy the source code
COPY . .

# Expose Next.js dev port
EXPOSE 3000

# Start next.js in dev mode
CMD ["npm", "run", "dev"]